# -*- coding: utf-8 -*-
"""251205-CC8_GPU-accelator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mpJvm2_DEcf4v4M3gxltTCKRckrX28dW
"""

import torch
from torchvision.models import MobileNet_V3_Small_Weights, mobilenet_v3_small, get_model, list_models
from torchvision.io import decode_image
from torchvision import transforms as T
import torch.nn.functional as F
import matplotlib.pyplot as plt
from tqdm import tqdm

to_img = T.ToPILImage()

weights = MobileNet_V3_Small_Weights.IMAGENET1K_V1
model = mobilenet_v3_small(weights=weights)
_ = model.eval()
preprocess = weights.transforms()
categories = weights.meta['categories']

list_models()
google = get_model('googlenet', weights='DEFAULT')

for parameter in google.parameters():
  parameter.requires_grad = False
  #tahle smycka se dela pro to aby se nepocitali gradienty uplne vsude, vsechny ty parametry nepotrebujou gradienty

torch.set_default_device('cuda') #odkaz na GPU, pouziva to GPU, cuda x cpu, cuda je nazev knihovny
#graf karty se vyvyjeli na vypocet obrazku, spu pocita linearne po polozkach, gpu muzes pocitat paralelne
#knihovna od nvidia, pro jine graf karty treba rocm
#AMD x nvidia
_ = google.to('cuda') #var to cuda, kdyz pridam '_ =' se nemusi vypisovat output v tomto okne
#to co python vytvori bude v cude, ale to co se nacte je normalne mimo, proto pridavam tuhle radku

[i[0] for i in google.named_children()]

activation = {}
def create_hook(name):
    def hook(m, i, o):
        activation[name] = o
    return hook

mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]
normalize = T.Normalize(mean=mean, std=std)

def postprocess(x):
  out = x*torch.tensor(std).view(1, -1, 1, 1) + torch.tensor(mean).view(1, -1, 1, 1)
  return out

# dummy = torch.randn(1,3,224,224)
# predictions = model(dummy)
# target = torch.zeros_like(predictions)
# n_class = 300
# target[:,n_class] = 1
# categories[n_class]

input = torch.rand(1,3,200,200)
input *=0.1
input +=0.5
out = to_img(input[0])
input = normalize(input)
input.requires_grad = True

out

augmentation = T.Compose([
    T.RandomHorizontalFlip(),
    T.ElasticTransform(10., ),
    T.RandomRotation(50),
])

def gradient_comp(input, model, n_idx, lr=0.1, neuron_inty=1, noise_inty=0, n_iter = 20):

  for i in range(n_iter):
    noise = torch.randn_like(input)*noise_inty
    predictions = model(input+noise)
    loss = predictions[:,n_idx].square().mean()
    loss *= neuron_inty

    optim_img = postprocess(input)
    clip_loss = (optim_img - optim_img.clip(0,1)).square().mean()
    loss += clip_loss

    pxl_inty = input.square().mean()
    loss += pxl_inty

    grad = torch.autograd.grad(loss, [input])[0]

    grd_mean = grad.mean()
    grd_std = grad.std()
    grad = (grad-grd_mean)/grd_std

    input = input + grad*lr

  return input


def gradient_comp_hook(input, model, n_idx, lr=0.1, neuron_inty=1, noise_inty=0, n_iter = 20, clamp=(-4,4)):

  for i in range(n_iter):
    # input = augmentation(input) #vypnu augmentaci pro to aby co pro video neudelalo vzdy nove random
    noise = torch.randn_like(input)*noise_inty
    predictions = model(input+noise)

    layer = [activation[key][:,n_idx].square().mean() for key in activation.keys()]

    loss = sum(layer)
    loss *= neuron_inty

    optim_img = postprocess(input)
    clip_loss = (optim_img - optim_img.clip(0,1)).square().mean()
    loss += clip_loss

    pxl_inty = input.square().mean()
    loss += pxl_inty

    grad = torch.autograd.grad(loss, [input])[0]

    grd_mean = grad.mean()
    grd_std = grad.std()
    grad = (grad-grd_mean)/grd_std

    input = input + grad*lr
    input = input.clip(-4,4)

  return input

torch.manual_seed(9)
input = torch.randn(1,3,300,300, requires_grad=True)*0.1

out = gradient_comp(input, google, 120, lr=0.12, neuron_inty=-100, noise_inty=0.3)
img_out = postprocess(out).clip(0,1)
img_file = to_img(img_out[0])
img_file

torch.linspace(1,3,5)
torch.logspace(-2,1,5)

torch.manual_seed(9)
n_octaves = 5
scale_factor = 1.5

# neuron_sched = torch.linspace(0.1,10,n_octaves)
neuron_sched = torch.logspace(-1,1,n_octaves)

input = torch.randn(1,3,64,64, requires_grad=True)*0.1
for i in range(n_octaves):
  grad_inty = neuron_sched[i]
  input = gradient_comp(input, google, 120, lr=0.07, neuron_inty=grad_inty, noise_inty=0.3)

  h,w = input.shape[-2:]
  h = int(h*scale_factor)
  w = int(w*scale_factor)
  out = input
  input = F.interpolate(input,(h,w), mode='bilinear')


img_out = postprocess(out).clip(0,1)
img_file = to_img(img_out[0])
img_file

activation = {}
# hook = google.conv1.register_forward_hook(create_hook('conv1'))
# hook1 = google.inception3a.register_forward_hook(create_hook('inc3a'))
# hook1.remove()
hook2 = google.inception4a.register_forward_hook(create_hook('inc4a'))
# hook2.remove()

torch.manual_seed(9)
n_octaves = 5
scale_factor = 1.5
n_neuron = 301

# neuron_sched = torch.linspace(0.1,10,n_octaves)
neuron_sched = torch.logspace(-1,1,n_octaves)

input = torch.randn(1,3,64,64, requires_grad=True)*0.1
for i in range(n_octaves-1): #pridam -1 pro gerovani videa
  grad_inty = -1 #neuron_sched[i]
  input = gradient_comp_hook(input, google, n_neuron, lr=0.05, neuron_inty=grad_inty, noise_inty=0.5, n_iter=20)
  h,w = input.shape[-2:]
  h = int(h*scale_factor)
  w = int(w*scale_factor)
  out = input
  input = F.interpolate(input,(h,w), mode='bilinear')

n_frames = 400
for i in tqdm(range(n_frames)):
   input = gradient_comp_hook(input, google, n_neuron, lr=0.03, neuron_inty=grad_inty, noise_inty=2.2, n_iter=30)
   input = T.ElasticTransform(5.)(input) #cislo. = float, funkce pro augmentace
   out = input
   img_out = postprocess(out).clip(0,1)
   img_file = to_img(img_out[0])
   img_file.save('out/frame%04d.jpg'%i) #iterace videa.. ukladani jednotlivych framu = generator nazvu soubotu
   #%04 znamena ze tam jsou 4x0 a d je cislo
   #lepsi ukladat do png a ne jpg, jpg je jenom rychlejsi

# img_out = postprocess(out).clip(0,1)
# img_file = to_img(img_out[0])
# img_file

#cilem je udrzet textury tak aby se udrezeli grandianty a pak to znamena ze to nebude rozmazane
#cilem je najit stabilitu

!ffmpeg -framerate 15 -i out/frame%04d.jpg -c:v libx264 -pix_fmt yuv420p output.mp4 -y
#spoustim sofware nebo neco tak proto !

#diffusion modely taky dopocitavaji oktavy taky, tohle je jen L. pyramid

activation.keys()

out.min(), out.max()

img_out = postprocess(input)
img_file = to_img(img_out[0])
# img_file.save('/content/7.jpg')
img_file

